---
abstract: 'RT-Extension-AjaxPreviewScrips Extension'
author:
  - 'Best Practical Solutions, LLC <modules@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-AjaxPreviewScrips
no_index:
  directory:
    - html
    - inc
    - static
  package:
    - HTML::Mason::Commands
    - RT::Record
    - RT::Ticket
    - RT::Transaction
requires:
  perl: 5.10.1
resources:
  license: http://opensource.org/licenses/gpl-license.php
  repository: https://github.com/bestpractical/rt-extension-ajaxpreviewscrips
version: '0.10'
x_module_install_rtx_version: '0.37'
x_requires_rt: 4.2.0
x_rt_too_new: 4.4.0
